services:
  learn_ms.api:
    image: learn_ms.api
    pull_policy: build
    container_name: LearnMS.Api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:8080
    env_file:
      - .env
    depends_on:
      learn_ms.database:
        condition: service_healthy
  learn_ms.database:
    image: postgres:16-alpine
    container_name: LearnMS.Database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - learn_ms_database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  learn_ms_database:
