// <auto-generated />
using System;
using System.Text.Json;
using LearnMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240902205511_Migrations_QuestiosnCreatedAt")]
    partial class Migrations_QuestiosnCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamEnrollment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId", "ExamId");

                    b.ToTable("ExamEnrollment");
                });

            modelBuilder.Entity("ExamSubmission", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumOfCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("NumOfQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("QuestionSubmissionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId", "ExamId");

                    b.ToTable("ExamSubmission");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderType")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.HasKey("Id", "ProviderType");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProviderId", "ProviderType");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ExpirationDays")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RenewalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LearnMS.API.Entities.CourseEnrollment", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CourseId", "StudentId");

                    b.ToTable("CourseEnrollment");
                });

            modelBuilder.Entity("LearnMS.API.Entities.CreditCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GeneratorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("CreditCodes");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpiryHours")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RetakePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("LearnMS.API.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExamId", "QuestionId");

                    b.ToTable("ExamQuestion");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Lecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ExpirationDays")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RenewalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureAsset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasColumnType("text");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.HasKey("AssetId", "LectureId");

                    b.ToTable("LectureAsset");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureAttendance", b =>
                {
                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AttendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LectureId", "StudentId");

                    b.ToTable("LectureAttendance");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureEnrollment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId", "LectureId");

                    b.ToTable("LectureEnrollment");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureHomework", b =>
                {
                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("LectureId", "StudentId");

                    b.ToTable("LectureHomework");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureQuiz", b =>
                {
                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("LectureId", "StudentId");

                    b.ToTable("LectureQuiz");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpirationHours")
                        .HasColumnType("integer");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal>("RenewalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LessonAttendance", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LessonId", "StudentId");

                    b.ToTable("LessonAttendance");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("LearnMS.API.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuestionId", "QuizId");

                    b.ToTable("QuizQuestion");
                });

            modelBuilder.Entity("LearnMS.API.Entities.QuizSubmission", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumOfCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("NumOfQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("QuestionSubmissionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuizId", "StudentId");

                    b.ToTable("QuizSubmission");
                });

            modelBuilder.Entity("LearnMS.API.Entities.StudentCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssistantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.ToTable("StudentCredit");
                });

            modelBuilder.Entity("LearnMS.API.Entities.StudentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("StudentEvent");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("LearnMS.API.Entities.Assistant", b =>
                {
                    b.HasBaseType("User");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Student", b =>
                {
                    b.HasBaseType("User");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<string>("DeviceKey")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Teacher", b =>
                {
                    b.HasBaseType("User");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ExamEnrollment", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Exam", "Exam")
                        .WithMany("ExamEnrollments")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("ExamEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExamSubmission", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamEnrollment", "ExamEnrollment")
                        .WithOne("Submission")
                        .HasForeignKey("ExamSubmission", "StudentId", "ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ExamEnrollment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Account", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnMS.API.Entities.CourseEnrollment", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Course", "Course")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnMS.API.Entities.CreditCode", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Assistant", null)
                        .WithMany()
                        .HasForeignKey("GeneratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LearnMS.API.Entities.Assistant", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LearnMS.API.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LearnMS.API.Entities.Exam", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LearnMS.API.Entities.ExamQuestion", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Lecture", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureAsset", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Asset", "Asset")
                        .WithMany("LectureAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Lecture", "Lecture")
                        .WithMany("LectureAssets")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureAttendance", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Lecture", "Lecture")
                        .WithMany("LectureAttendances")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("LectureAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureEnrollment", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Lecture", "Lecture")
                        .WithMany("LectureEnrollments")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("LectureEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureHomework", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Lecture", "Lecture")
                        .WithMany("LectureHomeworks")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("LectureHomeworks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LectureQuiz", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Lecture", "Lecture")
                        .WithMany("LectureQuizzes")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("LectureQuizzes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Lesson", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Lecture", "Lecture")
                        .WithMany("Lessons")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("LearnMS.API.Entities.LessonAttendance", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Lesson", "Lesson")
                        .WithMany("LessonAttendances")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("LessonAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Quiz", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Lecture", "Lecture")
                        .WithMany("Quizzes")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("LearnMS.API.Entities.QuizQuestion", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Question", "Question")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("LearnMS.API.Entities.QuizSubmission", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Quiz", "Quiz")
                        .WithMany("QuizSubmissions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("QuizSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnMS.API.Entities.StudentCredit", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Assistant", null)
                        .WithOne()
                        .HasForeignKey("LearnMS.API.Entities.StudentCredit", "AssistantId");

                    b.HasOne("LearnMS.API.Entities.Student", null)
                        .WithOne()
                        .HasForeignKey("LearnMS.API.Entities.StudentCredit", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnMS.API.Entities.StudentEvent", b =>
                {
                    b.HasOne("LearnMS.API.Entities.Student", "Student")
                        .WithMany("Events")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExamEnrollment", b =>
                {
                    b.Navigation("Submission");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Asset", b =>
                {
                    b.Navigation("LectureAssets");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Course", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("Exams");

                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Exam", b =>
                {
                    b.Navigation("ExamEnrollments");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Lecture", b =>
                {
                    b.Navigation("LectureAssets");

                    b.Navigation("LectureAttendances");

                    b.Navigation("LectureEnrollments");

                    b.Navigation("LectureHomeworks");

                    b.Navigation("LectureQuizzes");

                    b.Navigation("Lessons");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Lesson", b =>
                {
                    b.Navigation("LessonAttendances");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Question", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Quiz", b =>
                {
                    b.Navigation("QuizQuestions");

                    b.Navigation("QuizSubmissions");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("LearnMS.API.Entities.Student", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("Events");

                    b.Navigation("ExamEnrollments");

                    b.Navigation("LectureAttendances");

                    b.Navigation("LectureEnrollments");

                    b.Navigation("LectureHomeworks");

                    b.Navigation("LectureQuizzes");

                    b.Navigation("LessonAttendances");

                    b.Navigation("QuizSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
