/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** WithRequired type helpers */
type WithRequired<T, K extends keyof T> = T & { [P in K]-?: T[P] };

export interface paths {
  "/api/administration/teachers": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["CreateTeacherRequest"];
          "application/json": components["schemas"]["CreateTeacherRequest"];
          "text/json": components["schemas"]["CreateTeacherRequest"];
          "application/*+json": components["schemas"]["CreateTeacherRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/administration/assistants": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetAssistantsResponseSuccess"];
            "application/json": components["schemas"]["GetAssistantsResponseSuccess"];
            "text/json": components["schemas"]["GetAssistantsResponseSuccess"];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["CreateAssistantRequest"];
          "application/json": components["schemas"]["CreateAssistantRequest"];
          "text/json": components["schemas"]["CreateAssistantRequest"];
          "application/*+json": components["schemas"]["CreateAssistantRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/administration/assistants/{assistantId}": {
    get: {
      parameters: {
        path: {
          assistantId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetAssistantResponseSuccess"];
            "application/json": components["schemas"]["GetAssistantResponseSuccess"];
            "text/json": components["schemas"]["GetAssistantResponseSuccess"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          assistantId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          assistantId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateAssistantRequest"];
          "application/json": components["schemas"]["UpdateAssistantRequest"];
          "text/json": components["schemas"]["UpdateAssistantRequest"];
          "application/*+json": components["schemas"]["UpdateAssistantRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/administration/permissions": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetPermissionsResponseSuccess"];
            "application/json": components["schemas"]["GetPermissionsResponseSuccess"];
            "text/json": components["schemas"]["GetPermissionsResponseSuccess"];
          };
        };
      };
    };
  };
  "/api/administration/assistants/{assistantId}/incomes": {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        path: {
          assistantId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetAssistantIncomeResponseSuccess"];
            "application/json": components["schemas"]["GetAssistantIncomeResponseSuccess"];
            "text/json": components["schemas"]["GetAssistantIncomeResponseSuccess"];
          };
        };
      };
    };
  };
  "/api/administration/assistants/{assistantId}/claim": {
    post: {
      parameters: {
        path: {
          assistantId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/assets": {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          search?: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["AssetPageListSuccess"];
            "application/json": components["schemas"]["AssetPageListSuccess"];
            "text/json": components["schemas"]["AssetPageListSuccess"];
          };
        };
      };
    };
  };
  "/api/assets/delete": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": string[];
          "application/json": string[];
          "text/json": string[];
          "application/*+json": string[];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/assets/{fileId}": {
    get: {
      parameters: {
        path: {
          fileId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/auth": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StringApiResponseSuccess"];
            "application/json": components["schemas"]["StringApiResponseSuccess"];
            "text/json": components["schemas"]["StringApiResponseSuccess"];
          };
        };
      };
    };
  };
  "/api/auth/students/register": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["RegisterStudentRequest"];
          "application/json": components["schemas"]["RegisterStudentRequest"];
          "text/json": components["schemas"]["RegisterStudentRequest"];
          "application/*+json": components["schemas"]["RegisterStudentRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "text/plain": components["schemas"]["RegisterResultSuccess"];
            "application/json": components["schemas"]["RegisterResultSuccess"];
            "text/json": components["schemas"]["RegisterResultSuccess"];
          };
        };
      };
    };
  };
  "/api/auth/students/register-external": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["RegisterStudentExternalCommand"];
          "application/json": components["schemas"]["RegisterStudentExternalCommand"];
          "text/json": components["schemas"]["RegisterStudentExternalCommand"];
          "application/*+json": components["schemas"]["RegisterStudentExternalCommand"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "text/plain": components["schemas"]["RegisterResultSuccess"];
            "application/json": components["schemas"]["RegisterResultSuccess"];
            "text/json": components["schemas"]["RegisterResultSuccess"];
          };
        };
      };
    };
  };
  "/api/auth/login": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["LoginRequest"];
          "application/json": components["schemas"]["LoginRequest"];
          "text/json": components["schemas"]["LoginRequest"];
          "application/*+json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["LoginResultSuccess"];
            "application/json": components["schemas"]["LoginResultSuccess"];
            "text/json": components["schemas"]["LoginResultSuccess"];
          };
        };
      };
    };
  };
  "/api/auth/login-external": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["LoginExternalCommand"];
          "application/json": components["schemas"]["LoginExternalCommand"];
          "text/json": components["schemas"]["LoginExternalCommand"];
          "application/*+json": components["schemas"]["LoginExternalCommand"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["LoginResultSuccess"];
            "application/json": components["schemas"]["LoginResultSuccess"];
            "text/json": components["schemas"]["LoginResultSuccess"];
          };
        };
      };
    };
  };
  "/api/auth/verify-email": {
    get: {
      parameters: {
        query?: {
          token?: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/auth/forgot-password": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["ForgotPasswordRequest"];
          "application/json": components["schemas"]["ForgotPasswordRequest"];
          "text/json": components["schemas"]["ForgotPasswordRequest"];
          "application/*+json": components["schemas"]["ForgotPasswordRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/auth/reset-password": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["ResetPasswordRequest"];
          "application/json": components["schemas"]["ResetPasswordRequest"];
          "text/json": components["schemas"]["ResetPasswordRequest"];
          "application/*+json": components["schemas"]["ResetPasswordRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/buy": {
    post: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}": {
    get: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetStudentCourseResponseSuccess"];
            "application/json": components["schemas"]["GetStudentCourseResponseSuccess"];
            "text/json": components["schemas"]["GetStudentCourseResponseSuccess"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateCourseRequest"];
          "application/json": components["schemas"]["UpdateCourseRequest"];
          "text/json": components["schemas"]["UpdateCourseRequest"];
          "application/*+json": components["schemas"]["UpdateCourseRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetStudentCoursesResponseSuccess"];
            "application/json": components["schemas"]["GetStudentCoursesResponseSuccess"];
            "text/json": components["schemas"]["GetStudentCoursesResponseSuccess"];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["CreateCourseCommand"];
          "application/json": components["schemas"]["CreateCourseCommand"];
          "text/json": components["schemas"]["CreateCourseCommand"];
          "application/*+json": components["schemas"]["CreateCourseCommand"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["CreateCourseResponseSuccess"];
            "application/json": components["schemas"]["CreateCourseResponseSuccess"];
            "text/json": components["schemas"]["CreateCourseResponseSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/publish": {
    post: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/unpublish": {
    post: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/credit-codes": {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          search?: string;
          sortOrder?: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SingleCreditCodeItemPageListSuccess"];
            "application/json": components["schemas"]["SingleCreditCodeItemPageListSuccess"];
            "text/json": components["schemas"]["SingleCreditCodeItemPageListSuccess"];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["GenerateCreditCodesRequest"];
          "application/json": components["schemas"]["GenerateCreditCodesRequest"];
          "text/json": components["schemas"]["GenerateCreditCodesRequest"];
          "application/*+json": components["schemas"]["GenerateCreditCodesRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/credit-codes/redeem": {
    put: {
      parameters: {
        query?: {
          code?: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RedeemCreditCodeResponseSuccess"];
            "application/json": components["schemas"]["RedeemCreditCodeResponseSuccess"];
            "text/json": components["schemas"]["RedeemCreditCodeResponseSuccess"];
          };
        };
      };
    };
  };
  "/api/credit-codes/sell": {
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["SellCreditCodesRequest"];
          "application/json": components["schemas"]["SellCreditCodesRequest"];
          "text/json": components["schemas"]["SellCreditCodesRequest"];
          "application/*+json": components["schemas"]["SellCreditCodesRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SellCreditCodesResponseSuccess"];
            "application/json": components["schemas"]["SellCreditCodesResponseSuccess"];
            "text/json": components["schemas"]["SellCreditCodesResponseSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/exams/{examId}/buy": {
    post: operations["BuyExam"];
  };
  "/api/courses/{courseId}/exams/{examId}": {
    get: operations["GetExam"];
    delete: operations["DeleteExam"];
  };
  "/api/courses/{courseId}/exams": {
    put: operations["UpdateExam"];
  };
  "/api/courses/{courseId}/lectures/{lectureId}": {
    get: {
      parameters: {
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetStudentLectureResponseSuccess"];
            "application/json": components["schemas"]["GetStudentLectureResponseSuccess"];
            "text/json": components["schemas"]["GetStudentLectureResponseSuccess"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateLectureRequest"];
          "application/json": components["schemas"]["UpdateLectureRequest"];
          "text/json": components["schemas"]["UpdateLectureRequest"];
          "application/*+json": components["schemas"]["UpdateLectureRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/buy": {
    post: {
      parameters: {
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures": {
    post: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["CreateLectureRequest"];
          "application/json": components["schemas"]["CreateLectureRequest"];
          "text/json": components["schemas"]["CreateLectureRequest"];
          "application/*+json": components["schemas"]["CreateLectureRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/publish": {
    post: {
      parameters: {
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/unpublish": {
    post: {
      parameters: {
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/students/{studentId}/homework": {
    put: {
      parameters: {
        path: {
          lectureId: string;
          studentId: string;
          courseId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["ChangeLectureHomeworkScoreRequest"];
          "application/json": components["schemas"]["ChangeLectureHomeworkScoreRequest"];
          "text/json": components["schemas"]["ChangeLectureHomeworkScoreRequest"];
          "application/*+json": components["schemas"]["ChangeLectureHomeworkScoreRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/students/{studentId}/quiz": {
    put: {
      parameters: {
        path: {
          lectureId: string;
          studentId: string;
          courseId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["ChangeLectureQuizScoreRequest"];
          "application/json": components["schemas"]["ChangeLectureQuizScoreRequest"];
          "text/json": components["schemas"]["ChangeLectureQuizScoreRequest"];
          "application/*+json": components["schemas"]["ChangeLectureQuizScoreRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/students": {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          search?: string;
        };
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SingleLectureStudentPageListSuccess"];
            "application/json": components["schemas"]["SingleLectureStudentPageListSuccess"];
            "text/json": components["schemas"]["SingleLectureStudentPageListSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/assets": {
    put: {
      parameters: {
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": string[];
          "application/json": string[];
          "text/json": string[];
          "application/*+json": string[];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/lessons/{lessonId}": {
    get: {
      parameters: {
        path: {
          courseId: string;
          lectureId: string;
          lessonId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetStudentLessonResponse"];
            "application/json": components["schemas"]["GetStudentLessonResponse"];
            "text/json": components["schemas"]["GetStudentLessonResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          courseId: string;
          lectureId: string;
          lessonId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          lessonId: string;
          courseId: string;
          lectureId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateLessonRequest"];
          "application/json": components["schemas"]["UpdateLessonRequest"];
          "text/json": components["schemas"]["UpdateLessonRequest"];
          "application/*+json": components["schemas"]["UpdateLessonRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/lessons": {
    post: {
      parameters: {
        path: {
          lectureId: string;
          courseId: string;
        };
      };
      requestBody?: {
        content: {
          "multipart/form-data": {
            Title: string;
            Description: string;
            /** Format: double */
            RenewalPrice: number;
            /** Format: int32 */
            ExpirationHours: number;
          };
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/lessons/{lessonId}/start": {
    post: {
      parameters: {
        path: {
          lessonId: string;
          courseId: string;
          lectureId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/lessons/{lessonId}/renew": {
    post: {
      parameters: {
        path: {
          lessonId: string;
          courseId: string;
          lectureId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/lessons/{lessonId}/video/validate": {
    post: {
      parameters: {
        path: {
          lessonId: string;
          courseId: string;
          lectureId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ValidateLessonVideoStatusResponseSuccess"];
            "application/json": components["schemas"]["ValidateLessonVideoStatusResponseSuccess"];
            "text/json": components["schemas"]["ValidateLessonVideoStatusResponseSuccess"];
          };
        };
      };
    };
  };
  "/api/profile": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetProfileResponseSuccess"];
            "application/json": components["schemas"]["GetProfileResponseSuccess"];
            "text/json": components["schemas"]["GetProfileResponseSuccess"];
          };
        };
      };
    };
    patch: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateStudentProfileRequest"];
          "application/json": components["schemas"]["UpdateStudentProfileRequest"];
          "text/json": components["schemas"]["UpdateStudentProfileRequest"];
          "application/*+json": components["schemas"]["UpdateStudentProfileRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/questions": {
    get: {
      parameters: {
        query?: {
          Search?: string;
          Page?: number;
          PageSize?: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["QuestionPageListSuccess"];
            "application/json": components["schemas"]["QuestionPageListSuccess"];
            "text/json": components["schemas"]["QuestionPageListSuccess"];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "multipart/form-data": {
            Text?: string;
            Description?: string;
            /** Format: binary */
            Image?: string;
            /** Format: double */
            ValueCorrect?: number;
            /** Format: double */
            ValueTolerance?: number;
            MultipleCorrect?: string;
            MultipleChoices?: string[];
          };
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/questions/{questionId}": {
    delete: {
      parameters: {
        path: {
          questionId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/quizzes/{quizId}": {
    get: operations["getQuiz"];
    delete: {
      parameters: {
        path: {
          courseId: string;
          lectureId: string;
          quizId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/quizzes/{quizId}/submit": {
    post: {
      parameters: {
        path: {
          courseId: string;
          lectureId: string;
          quizId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["SubmitQuizRequest"];
          "application/json": components["schemas"]["SubmitQuizRequest"];
          "text/json": components["schemas"]["SubmitQuizRequest"];
          "application/*+json": components["schemas"]["SubmitQuizRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/courses/{courseId}/lectures/{lectureId}/quizzes": {
    put: {
      parameters: {
        path: {
          courseId: string;
          lectureId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateQuizRequest"];
          "application/json": components["schemas"]["UpdateQuizRequest"];
          "text/json": components["schemas"]["UpdateQuizRequest"];
          "application/*+json": components["schemas"]["UpdateQuizRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["UpdateQuizResponseSuccess"];
            "application/json": components["schemas"]["UpdateQuizResponseSuccess"];
            "text/json": components["schemas"]["UpdateQuizResponseSuccess"];
          };
        };
      };
    };
  };
  "/api/students": {
    get: {
      parameters: {
        query?: {
          search?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SingleStudentPageListSuccess"];
            "application/json": components["schemas"]["SingleStudentPageListSuccess"];
            "text/json": components["schemas"]["SingleStudentPageListSuccess"];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["CreateStudentRequest"];
          "application/json": components["schemas"]["CreateStudentRequest"];
          "text/json": components["schemas"]["CreateStudentRequest"];
          "application/*+json": components["schemas"]["CreateStudentRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/students/{studentId}": {
    get: {
      parameters: {
        path: {
          studentId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetStudentResponseSuccess"];
            "application/json": components["schemas"]["GetStudentResponseSuccess"];
            "text/json": components["schemas"]["GetStudentResponseSuccess"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          studentId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          studentId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateStudentRequest"];
          "application/json": components["schemas"]["UpdateStudentRequest"];
          "text/json": components["schemas"]["UpdateStudentRequest"];
          "application/*+json": components["schemas"]["UpdateStudentRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
  "/api/students/{studentId}/credit": {
    post: {
      parameters: {
        path: {
          studentId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["AddStudentCreditRequest"];
          "application/json": components["schemas"]["AddStudentCreditRequest"];
          "text/json": components["schemas"]["AddStudentCreditRequest"];
          "application/*+json": components["schemas"]["AddStudentCreditRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ObjectSuccess"];
            "application/json": components["schemas"]["ObjectSuccess"];
            "text/json": components["schemas"]["ObjectSuccess"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AddStudentCreditRequest: {
      /** Format: double */
      amount?: number;
    };
    Asset: {
      id: string;
      name: string;
      type: components["schemas"]["AssetType"];
    };
    AssetPageList: {
      items: readonly components["schemas"]["Asset"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    AssetPageListSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["AssetPageList"];
    };
    /** @enum {string} */
    AssetType: "Pdf" | "Image" | "Unknown";
    ChangeLectureHomeworkScoreRequest: {
      /** Format: double */
      score?: number;
    };
    ChangeLectureQuizScoreRequest: {
      /** Format: double */
      score?: number;
    };
    CreateAssistantRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    CreateCourseCommand: {
      title?: string;
    };
    CreateCourseResponse: {
      /** Format: uuid */
      id?: string;
    };
    CreateCourseResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["CreateCourseResponse"];
    };
    CreateLectureRequest: {
      title: string;
    };
    CreateStudentRequest: {
      /** Format: email */
      email: string;
      password: string;
      school: string;
      fullName: string;
      phoneNumber: string;
      parentPhoneNumber: string;
      studentCode: string;
      level: components["schemas"]["StudentLevel"];
    };
    CreateTeacherRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    CreditCode: {
      code?: string;
      /** Format: double */
      value?: number;
      /** Format: uuid */
      generatorId?: string | null;
      /** Format: uuid */
      sellerId?: string | null;
      /** Format: uuid */
      studentId?: string | null;
      status?: components["schemas"]["CreditCodeStatus"];
      /** Format: date-time */
      generatedAt?: string;
      /** Format: date-time */
      soldAt?: string | null;
      /** Format: date-time */
      redeemedAt?: string | null;
      /** Format: date-time */
      claimedAt?: string | null;
    };
    CreditCodeGenerator: {
      /** Format: uuid */
      id?: string;
      email?: string;
    };
    CreditCodeRedeemer: {
      /** Format: uuid */
      id?: string;
      email?: string;
      /** Format: date-time */
      redeemedAt?: string;
    };
    CreditCodeSeller: {
      /** Format: uuid */
      id?: string;
      email?: string;
    };
    /** @enum {string} */
    CreditCodeStatus: "Fresh" | "Sold" | "Redeemed";
    ExamDashboard: WithRequired<{
      $type: "ExamDashboard";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: int32 */
      passCount: number;
      /** Format: double */
      price: number;
      /** Format: double */
      retakePrice: number;
      resultType: components["schemas"]["ResultType"];
      questions: components["schemas"]["Question"][];
    } & Omit<components["schemas"]["ExamResult"], "$type">, "description" | "id" | "passCount" | "price" | "questions" | "resultType" | "retakePrice" | "title">;
    ExamHidden: WithRequired<{
      $type: "ExamHidden";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: int32 */
      passCount: number;
      /** Format: int32 */
      numOfQuestions: number;
      multipleChoiceQuestions: components["schemas"]["MultipleChoiceWithStudentAnswer"][];
      valueToleranceQuestions: components["schemas"]["ValueToleranceWithStudentAnswer"][];
    } & Omit<components["schemas"]["ExamResult"], "$type">, "description" | "id" | "multipleChoiceQuestions" | "numOfQuestions" | "passCount" | "title" | "valueToleranceQuestions">;
    ExamNotAnswered: WithRequired<{
      $type: "ExamNotAnswered";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      multipleChoiceQuestions: components["schemas"]["MultipleChoiceNotAnswered"][];
      valueToleranceQuestions: components["schemas"]["ValueToleranceNotAnswered"][];
      /** Format: int32 */
      passCount: number;
    } & Omit<components["schemas"]["ExamResult"], "$type">, "description" | "id" | "multipleChoiceQuestions" | "passCount" | "title" | "valueToleranceQuestions">;
    ExamNotBought: WithRequired<{
      $type: "ExamNotBought";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: double */
      price: number;
      /** Format: int32 */
      passCount: number;
      /** Format: int32 */
      numOfQuestions: number;
    } & Omit<components["schemas"]["ExamResult"], "$type">, "description" | "id" | "numOfQuestions" | "passCount" | "price" | "title">;
    ExamResult: {
      $type: string;
    };
    ExamResultOnly: WithRequired<{
      $type: "ExamResultOnly";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: int32 */
      passCount: number;
      /** Format: int32 */
      numOfQuestions: number;
      /** Format: int32 */
      numOfCorrect: number;
      /** Format: double */
      retakePrice: number;
      multipleChoiceQuestions: components["schemas"]["MultipleChoiceWithStudentAnswer"][];
      valueToleranceQuestions: components["schemas"]["ValueToleranceWithStudentAnswer"][];
    } & Omit<components["schemas"]["ExamResult"], "$type">, "description" | "id" | "multipleChoiceQuestions" | "numOfCorrect" | "numOfQuestions" | "passCount" | "retakePrice" | "title" | "valueToleranceQuestions">;
    ExamResultSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["ExamDashboard"] | components["schemas"]["ExamNotBought"] | components["schemas"]["ExamNotAnswered"] | components["schemas"]["ExamHidden"] | components["schemas"]["ExamResultOnly"] | components["schemas"]["ExamResultWithAnswer"] | null;
    };
    ExamResultWithAnswer: WithRequired<{
      $type: "ExamResultWithAnswer";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: int32 */
      passCount: number;
      /** Format: int32 */
      numOfQuestions: number;
      /** Format: double */
      retakePrice: number;
      /** Format: int32 */
      numOfCorrect: number;
      multipleChoiceQuestions: components["schemas"]["MultipleChoiceWithCorrectAnswer"][];
      valueToleranceQuestions: components["schemas"]["ValueToleranceWithCorrectAnswer"][];
    } & Omit<components["schemas"]["ExamResult"], "$type">, "description" | "id" | "multipleChoiceQuestions" | "numOfCorrect" | "numOfQuestions" | "passCount" | "retakePrice" | "title" | "valueToleranceQuestions">;
    ForgotPasswordRequest: {
      /** Format: email */
      email: string;
    };
    GenerateCreditCodesRequest: {
      /** Format: int32 */
      count: number;
      /** Format: double */
      value: number;
    };
    GetAssistantIncomeResponse: {
      /** Format: double */
      unClaimedIncome?: number;
      /** Format: double */
      totalIncome?: number;
      data?: components["schemas"]["SingleAssistantIncomePageList"];
    };
    GetAssistantIncomeResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetAssistantIncomeResponse"];
    };
    GetAssistantResponse: {
      /** Format: uuid */
      id?: string;
      email?: string;
      permissions?: components["schemas"]["Permission"][];
    };
    GetAssistantResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetAssistantResponse"];
    };
    GetAssistantsResponse: {
      items?: components["schemas"]["SingleAssistant"][];
    };
    GetAssistantsResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetAssistantsResponse"];
    };
    GetPermissionsResponse: {
      items?: components["schemas"]["Permission"][];
    };
    GetPermissionsResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetPermissionsResponse"];
    };
    GetProfileResponse: {
      /** Format: uuid */
      id?: string;
      email?: string;
      fullName?: string | null;
      phoneNumber?: string | null;
      parentPhoneNumber?: string | null;
      studentCode?: string | null;
      school?: string | null;
      level?: components["schemas"]["StudentLevel"];
      profilePicture?: string | null;
      permissions?: components["schemas"]["Permission"][] | null;
      role?: string;
      /** Format: double */
      credits?: number | null;
    };
    GetProfileResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetProfileResponse"];
    };
    GetStudentCourseResponse: {
      /** Format: date-time */
      expiresAt?: string | null;
      items?: components["schemas"]["SingleStudentCourseItem"][];
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string | null;
      imageUrl?: string | null;
      level?: components["schemas"]["StudentLevel"];
      enrollment?: string;
      /** Format: double */
      price?: number | null;
      /** Format: double */
      renewalPrice?: number | null;
      /** Format: int32 */
      expirationDays?: number | null;
    };
    GetStudentCourseResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetStudentCourseResponse"];
    };
    GetStudentCoursesResponse: {
      items?: components["schemas"]["SingleStudentCourse"][];
    };
    GetStudentCoursesResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetStudentCoursesResponse"];
    };
    GetStudentLectureResponse: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string | null;
      imageUrl?: string | null;
      /** Format: double */
      price?: number | null;
      /** Format: double */
      renewalPrice?: number | null;
      items?: components["schemas"]["SingleLectureItem"][];
      /** Format: date-time */
      expiresAt?: string | null;
      enrollment?: string | null;
      assets?: components["schemas"]["Asset"][];
    };
    GetStudentLectureResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetStudentLectureResponse"];
    };
    GetStudentLessonResponse: {
      /** Format: uuid */
      id?: string;
      title?: string;
      /** Format: int32 */
      expirationHours?: number;
      /** Format: double */
      renewalPrice?: number;
      description?: string;
      enrollment?: string;
      /** Format: date-time */
      expiresAt?: string | null;
      videoOTP?: components["schemas"]["VideoOTP"];
    };
    GetStudentResponse: {
      /** Format: uuid */
      id?: string;
      email?: string;
      profilePicture?: string | null;
      fullName?: string;
      phoneNumber?: string;
      parentPhoneNumber?: string;
      studentCode?: string;
      password?: string | null;
      isVerified?: boolean;
      schoolName?: string;
      /** Format: double */
      credit?: number;
      level?: components["schemas"]["StudentLevel"];
    };
    GetStudentResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["GetStudentResponse"];
    };
    /** @enum {string} */
    IncomeType: "CodeSold" | "StudentCredit";
    LoginExternalCommand: {
      token?: string;
      provider?: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginResult: {
      /** Format: uuid */
      id: string;
      token: string;
      role: components["schemas"]["UserRole"];
      deviceKey: string;
    };
    LoginResultSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["LoginResult"];
    };
    MultipleChoiceNotAnswered: {
      /** Format: uuid */
      id: string;
      text: string;
      description: string;
      image: string;
      choices: string[];
    };
    MultipleChoiceQuestion: WithRequired<{
      $type: "MultipleChoiceQuestion";
      correctAnswer: string;
      choices: string[];
      typename: string;
    } & Omit<components["schemas"]["QuestionBody"], "$type">, "choices" | "correctAnswer" | "typename">;
    MultipleChoiceWithCorrectAnswer: {
      /** Format: uuid */
      id: string;
      text: string;
      description: string;
      image: string;
      choices: string[];
      correctAnswer: string;
      studentAnswer: string;
      isCorrect: boolean;
    };
    MultipleChoiceWithStudentAnswer: {
      /** Format: uuid */
      id: string;
      text: string;
      description: string;
      image: string;
      choices: string[];
      studentAnswer: string;
    };
    ObjectSuccess: {
      status?: boolean;
      message?: string | null;
      data?: unknown;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    Permission: 0 | 1 | 2 | 3 | 4 | 5;
    /** @enum {string} */
    ProviderType: "Google" | "Local";
    Question: {
      /** Format: uuid */
      id: string;
      text: string;
      description: string;
      image?: string | null;
      /** Format: date-time */
      createdAt: string;
      body: components["schemas"]["MultipleChoiceQuestion"] | components["schemas"]["ValueToleranceQuestion"];
    };
    QuestionAnswer: {
      /** Format: uuid */
      questionId: string;
      answer: string;
    };
    QuestionBody: {
      $type: string;
      typename: string;
    };
    QuestionPageList: {
      items: readonly components["schemas"]["Question"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    QuestionPageListSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["QuestionPageList"];
    };
    QuizDashboard: WithRequired<{
      $type: "QuizDashboard";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: int32 */
      passCount: number;
      resultType: components["schemas"]["ResultType"];
      questions: components["schemas"]["Question"][];
      typename?: string;
    } & Omit<components["schemas"]["QuizResult"], "$type">, "description" | "id" | "passCount" | "questions" | "resultType" | "title">;
    QuizHidden: WithRequired<{
      $type: "QuizHidden";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: int32 */
      passCount: number;
      /** Format: int32 */
      numOfQuestions: number;
      multipleChoiceQuestions: components["schemas"]["MultipleChoiceWithStudentAnswer"][];
      valueToleranceQuestions: components["schemas"]["ValueToleranceWithStudentAnswer"][];
      typename: string;
    } & Omit<components["schemas"]["QuizResult"], "$type">, "description" | "id" | "multipleChoiceQuestions" | "numOfQuestions" | "passCount" | "title" | "typename" | "valueToleranceQuestions">;
    QuizNotAnswered: WithRequired<{
      $type: "QuizNotAnswered";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      multipleChoiceQuestions: components["schemas"]["MultipleChoiceNotAnswered"][];
      valueToleranceQuestions: components["schemas"]["ValueToleranceNotAnswered"][];
      /** Format: int32 */
      passCount: number;
      typename: string;
    } & Omit<components["schemas"]["QuizResult"], "$type">, "description" | "id" | "multipleChoiceQuestions" | "passCount" | "title" | "typename" | "valueToleranceQuestions">;
    QuizResult: {
      $type: string;
      typename: string;
    };
    QuizResultOnly: WithRequired<{
      $type: "QuizResultOnly";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: int32 */
      passCount: number;
      /** Format: int32 */
      numOfQuestions: number;
      /** Format: int32 */
      numOfCorrect: number;
      multipleChoiceQuestions: components["schemas"]["MultipleChoiceWithStudentAnswer"][];
      valueToleranceQuestions: components["schemas"]["ValueToleranceWithStudentAnswer"][];
      typename: string;
    } & Omit<components["schemas"]["QuizResult"], "$type">, "description" | "id" | "multipleChoiceQuestions" | "numOfCorrect" | "numOfQuestions" | "passCount" | "title" | "typename" | "valueToleranceQuestions">;
    QuizResultSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["QuizDashboard"] | components["schemas"]["QuizNotAnswered"] | components["schemas"]["QuizHidden"] | components["schemas"]["QuizResultOnly"] | components["schemas"]["QuizResultWithAnswer"] | null;
    };
    QuizResultWithAnswer: WithRequired<{
      $type: "QuizResultWithAnswer";
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      /** Format: int32 */
      passCount: number;
      /** Format: int32 */
      numOfQuestions: number;
      /** Format: int32 */
      numOfCorrect: number;
      multipleChoiceQuestions: components["schemas"]["MultipleChoiceWithCorrectAnswer"][];
      valueToleranceQuestions: components["schemas"]["ValueToleranceWithCorrectAnswer"][];
      typename: string;
    } & Omit<components["schemas"]["QuizResult"], "$type">, "description" | "id" | "multipleChoiceQuestions" | "numOfCorrect" | "numOfQuestions" | "passCount" | "title" | "typename" | "valueToleranceQuestions">;
    RedeemCreditCodeResponse: {
      /** Format: double */
      value?: number;
    };
    RedeemCreditCodeResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["RedeemCreditCodeResponse"];
    };
    RegisterResult: {
      /** Format: uuid */
      id?: string;
    };
    RegisterResultSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["RegisterResult"];
    };
    RegisterStudentExternalCommand: {
      school: string;
      fullName: string;
      phoneNumber: string;
      parentPhoneNumber: string;
      studentCode: string;
      level: components["schemas"]["StudentLevel"];
      token: string;
      provider: components["schemas"]["ProviderType"];
    };
    RegisterStudentRequest: {
      email?: string;
      password?: string;
      school?: string;
      fullName?: string;
      phoneNumber?: string;
      parentPhoneNumber?: string;
      studentCode?: string;
      level?: components["schemas"]["StudentLevel"];
    };
    ResetPasswordRequest: {
      password: string;
      token: string;
    };
    /** @enum {string} */
    ResultType: "Hidden" | "ResultOnly" | "ResultWithAnswer";
    SellCreditCodesRequest: {
      codes: string[];
    };
    SellCreditCodesResponse: {
      creditCodes?: components["schemas"]["CreditCode"][];
    };
    SellCreditCodesResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["SellCreditCodesResponse"];
    };
    SingleAssistant: {
      /** Format: uuid */
      id?: string;
      email?: string;
      permissions?: components["schemas"]["Permission"][];
    };
    SingleAssistantIncome: {
      type?: components["schemas"]["IncomeType"];
      /** Format: double */
      amount?: number;
      code?: string | null;
      /** Format: uuid */
      studentId?: string | null;
      /** Format: date-time */
      happenedAt?: string;
      /** Format: date-time */
      claimedAt?: string | null;
    };
    SingleAssistantIncomePageList: {
      items: readonly components["schemas"]["SingleAssistantIncome"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    SingleCourseItem: {
      $type: string;
      /** Format: uuid */
      id?: string;
      title?: string;
      /** Format: int32 */
      order?: number;
      /** Format: double */
      price?: number | null;
      /** Format: double */
      renewalPrice?: number | null;
      type?: string;
      imageUrl?: string | null;
    };
    SingleCreditCodeItem: {
      code?: string;
      /** Format: double */
      value?: number;
      status?: components["schemas"]["CreditCodeStatus"];
      generator?: components["schemas"]["CreditCodeGenerator"];
      /** Format: date-time */
      generatedAt?: string;
      /** Format: date-time */
      soldAt?: string | null;
      seller?: components["schemas"]["CreditCodeSeller"];
      redeemer?: components["schemas"]["CreditCodeRedeemer"];
    };
    SingleCreditCodeItemPageList: {
      items: readonly components["schemas"]["SingleCreditCodeItem"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    SingleCreditCodeItemPageListSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["SingleCreditCodeItemPageList"];
    };
    SingleLectureItem: {
      /** Format: uuid */
      id?: string;
      title?: string;
      type?: string;
      description?: string | null;
      /** Format: int32 */
      order?: number;
    };
    SingleLectureStudent: {
      /** Format: uuid */
      id?: string;
      studentCode?: string;
      fullName?: string;
      email?: string;
      /** Format: double */
      homeworkScore?: number | null;
      attended?: boolean;
    };
    SingleLectureStudentPageList: {
      items: readonly components["schemas"]["SingleLectureStudent"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    SingleLectureStudentPageListSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["SingleLectureStudentPageList"];
    };
    SingleStudent: {
      /** Format: uuid */
      id?: string;
      email?: string;
      profilePicture?: string | null;
      fullName?: string;
      phoneNumber?: string;
      parentPhoneNumber?: string;
      studentCode?: string;
      isVerified?: boolean;
      schoolName?: string;
      /** Format: double */
      credit?: number;
      level?: components["schemas"]["StudentLevel"];
    };
    SingleStudentCourse: {
      /** Format: date-time */
      expiresAt?: string | null;
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string | null;
      imageUrl?: string | null;
      level?: components["schemas"]["StudentLevel"];
      /** Format: double */
      price?: number | null;
      /** Format: double */
      renewalPrice?: number | null;
      enrollment?: string | null;
    };
    SingleStudentCourseItem: ({
      $type: "SingleStudentCourseItem";
      enrollment?: string;
      /** Format: date-time */
      expiresAt?: string | null;
    }) & Omit<components["schemas"]["SingleCourseItem"], "$type">;
    SingleStudentPageList: {
      items: readonly components["schemas"]["SingleStudent"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    SingleStudentPageListSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["SingleStudentPageList"];
    };
    StringApiResponse: {
      typename?: string;
    };
    StringApiResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["StringApiResponse"];
    };
    /** @enum {string} */
    StudentLevel: "Level0" | "Level1" | "Level2" | "Level3";
    SubmitQuizRequest: {
      questionAnswers: components["schemas"]["QuestionAnswer"][];
    };
    UpdateAssistantRequest: {
      password?: string | null;
      permissions?: components["schemas"]["Permission"][] | null;
    };
    UpdateCourseRequest: {
      title?: string | null;
      description?: string | null;
      /** Format: double */
      price?: number | null;
      /** Format: double */
      renewalPrice?: number | null;
      level?: components["schemas"]["StudentLevel"];
      /** Format: int32 */
      expirationDays?: number | null;
      /** Format: uri */
      imageUrl?: string | null;
    };
    UpdateExamRequest: {
      /** Format: uuid */
      id?: string | null;
      title: string;
      description: string;
      resultType: components["schemas"]["ResultType"];
      /** Format: double */
      price: number;
      /** Format: double */
      retakePrice: number;
      /** Format: int32 */
      passCount: number;
      questions: string[];
    };
    UpdateExamResponse: {
      /** Format: uuid */
      id: string;
      title: string;
      description: string;
      resultType: components["schemas"]["ResultType"];
      /** Format: int32 */
      passCount: number;
      questions: components["schemas"]["Question"][];
      /** Format: double */
      price: number;
      /** Format: double */
      retakePrice: number;
    };
    UpdateExamResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["UpdateExamResponse"];
    };
    UpdateLectureRequest: {
      /** Format: uuid */
      courseId?: string;
      title?: string | null;
      description?: string | null;
      /** Format: double */
      price?: number | null;
      /** Format: uri */
      imageUrl?: string | null;
      /** Format: double */
      renewalPrice?: number | null;
      /** Format: int32 */
      expirationDays?: number | null;
    };
    UpdateLessonRequest: {
      title?: string | null;
      description?: string | null;
      /** Format: double */
      renewalPrice?: number | null;
      /** Format: int32 */
      expirationHours?: number | null;
      videoId?: string | null;
    };
    UpdateQuizRequest: {
      /** Format: uuid */
      id?: string | null;
      title: string;
      description: string;
      resultType: components["schemas"]["ResultType"];
      /** Format: int32 */
      passCount: number;
      questions?: string[];
    };
    UpdateQuizResponse: {
      /** Format: uuid */
      id?: string | null;
      title?: string;
      description?: string;
      resultType?: components["schemas"]["ResultType"];
      /** Format: int32 */
      passCount?: number;
      questions?: components["schemas"]["Question"][];
    };
    UpdateQuizResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["UpdateQuizResponse"];
    };
    UpdateStudentProfileRequest: {
      fullName?: string | null;
      /** Format: uri */
      profilePicture?: string | null;
      phoneNumber?: string | null;
      parentPhoneNumber?: string | null;
      studentCode?: string | null;
      schoolName?: string | null;
      level?: components["schemas"]["StudentLevel"];
    };
    UpdateStudentRequest: {
      fullName?: string | null;
      parentPhoneNumber?: string | null;
      studentCode?: string | null;
      phoneNumber?: string | null;
      schoolName?: string | null;
      password?: string | null;
      level?: components["schemas"]["StudentLevel"];
    };
    /** @enum {string} */
    UserRole: "Teacher" | "Assistant" | "Student";
    ValidateLessonVideoStatusResponse: {
      $type: "ValidateLessonVideoStatusResponse";
    } & Omit<components["schemas"]["ValidateLessonVideoStatusResult"], "$type">;
    ValidateLessonVideoStatusResponseSuccess: {
      status?: boolean;
      message?: string | null;
      data?: components["schemas"]["ValidateLessonVideoStatusResponse"];
    };
    ValidateLessonVideoStatusResult: {
      $type: string;
      videoId?: string;
      status?: string;
    };
    ValueToleranceNotAnswered: {
      /** Format: uuid */
      id: string;
      text: string;
      description: string;
      image: string;
      /** Format: double */
      tolerance: number;
    };
    ValueToleranceQuestion: WithRequired<{
      $type: "ValueToleranceQuestion";
      /** Format: double */
      correctAnswer: number;
      /** Format: double */
      tolerance: number;
      typename: string;
    } & Omit<components["schemas"]["QuestionBody"], "$type">, "correctAnswer" | "tolerance" | "typename">;
    ValueToleranceWithCorrectAnswer: {
      /** Format: uuid */
      id: string;
      text: string;
      description: string;
      image: string;
      /** Format: double */
      tolerance: number;
      /** Format: double */
      correctAnswer: number;
      /** Format: double */
      studentAnswer: number;
      isCorrect: boolean;
    };
    ValueToleranceWithStudentAnswer: {
      /** Format: uuid */
      id: string;
      text: string;
      description: string;
      image: string;
      /** Format: double */
      tolerance: number;
      /** Format: double */
      studentAnswer: number;
    };
    VideoOTP: {
      otp?: string;
      playbackInfo?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  BuyExam: {
    parameters: {
      path: {
        examId: string;
        courseId: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "text/plain": components["schemas"]["ObjectSuccess"];
          "application/json": components["schemas"]["ObjectSuccess"];
          "text/json": components["schemas"]["ObjectSuccess"];
        };
      };
    };
  };
  GetExam: {
    parameters: {
      path: {
        courseId: string;
        examId: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "text/plain": components["schemas"]["ExamResultSuccess"];
          "application/json": components["schemas"]["ExamResultSuccess"];
          "text/json": components["schemas"]["ExamResultSuccess"];
        };
      };
    };
  };
  DeleteExam: {
    parameters: {
      path: {
        courseId: string;
        examId: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "text/plain": components["schemas"]["ObjectSuccess"];
          "application/json": components["schemas"]["ObjectSuccess"];
          "text/json": components["schemas"]["ObjectSuccess"];
        };
      };
    };
  };
  UpdateExam: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody?: {
      content: {
        "application/json-patch+json": components["schemas"]["UpdateExamRequest"];
        "application/json": components["schemas"]["UpdateExamRequest"];
        "text/json": components["schemas"]["UpdateExamRequest"];
        "application/*+json": components["schemas"]["UpdateExamRequest"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "text/plain": components["schemas"]["UpdateExamResponseSuccess"];
          "application/json": components["schemas"]["UpdateExamResponseSuccess"];
          "text/json": components["schemas"]["UpdateExamResponseSuccess"];
        };
      };
    };
  };
  getQuiz: {
    parameters: {
      path: {
        courseId: string;
        lectureId: string;
        quizId: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "text/plain": components["schemas"]["QuizResultSuccess"];
          "application/json": components["schemas"]["QuizResultSuccess"];
          "text/json": components["schemas"]["QuizResultSuccess"];
        };
      };
    };
  };
}
